### ISSUE TITLE
Update js file registration to Craft 3 class

### ISSUE THREAD

**Issue by lindseybradford** [TelegraphCreative/TACWA.org#3]
Replace Craft 2 `{% includeJsFile…` with Craft 3 `{% do view.registerJsFile…`:

- [ ] https://github.com/TelegraphCreative/TACWA.org/blob/6e91d74d90b31430c549182ad9840d5a621db69d/templates/static/forms/logged-in--manage-members.twig#L76

- [ ] https://github.com/TelegraphCreative/TACWA.org/blob/6e91d74d90b31430c549182ad9840d5a621db69d/templates/static/forms/logged-in--manage-members--invite.twig#L90

Example: `{% do view.registerJsFile('path/to/file.js') %}`
Example using mix: `{% do view.registerJsFile( mix('/js/app.js') ) %}`

**Comment by tylernford** [comment]
@lindseybradford Taken care of!
